### ISSUE TITLE
[Feature Request] kubernetes support 

### ISSUE THREAD

**Issue by moinologics** [devforth/OnLogs#2]
Any plan to add kubernetes support? Specially for containerd backend.

**Comment by LbP22** [comment]
It should be supported from the box, but will check and get back to you with an example of usage

**Comment by moinologics** [comment]
in containerd backend (k3s cluster), I'm not understanding where to find .sock file

**Comment by LbP22** [comment]
I haven't tested it yet, but as I've understood, this example should help.
I'll research it better by my own later, 
```
apiVersion: v1
kind: Pod
metadata:
  name: privileged-pod
spec:
  containers:
  - name: onlogs
    image: devforth/onlogs:latest
    securityContext:
      privileged: true # privilegies configuring
  securityContext:
    runAsUser: 0 # run as user with ID 0 (root)
```

**Comment by LbP22** [comment]
Simply for kubernetes, this one worked for me:

```
apiVersion: v1
kind: Pod
metadata:
  name: privileged-pod
spec:
  containers:
  - name: onlogs
    image: devforth/onlogs:latest
    env:
      - name: ADMIN_USERNAME
        value: admin
      - name: ADMIN_PASSWORD
        value: admin
      - name: PORT
        value: "9876"
    volumeMounts:
      - name: onlogs-volume
        mountPath: /leveldb
      - name: docker-socket
        mountPath: /var/run/docker.sock
      - name: hostname
        mountPath: /etc/hostname
    ports:
      - containerPort: 9876

    securityContext:
      privileged: true # privilegies configuring
  securityContext:
    runAsUser: 0 # run as user with ID 0 (root)
  volumes:
    - name: onlogs-volume
      hostPath:
        path: /leveldb
        type: DirectoryOrCreate
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
        type: Socket
    - name: hostname
      hostPath:
        path: /etc/hostname
        type: FileOrCreate
```

But containerd support is another question. I'll research this and will see how different it's socket works comparing to dockers one
